---
- name: Install prerequisites
  ansible.builtin.package:
    name: "{{ item }}"
  loop: "{{ downloader_prereq }}"

- name: Download and Expand archive
  ansible.builtin.unarchive:
    src: "{{ downloader_archive_url }}"
    dest: "{{ downloader_archive_dest }}"
    remote_src: yes
    validate_certs: false

- name: Move executable
  ansible.builtin.copy:
    remote_src: true
    src: "{{ downloader_exec_src }}"
    dest: "{{ downloader_exec_dest }}"
    mode: "{{ downloader_exec_mode | default('755') }}"
