---
- name: Download Release
  ansible.builtin.get_url:
    url: "{{ mri_download_url }}"
    dest: "{{ mri_download_dest }}"

- name: Expand Archive
  ansible.builtin.unarchive:
    src: "{{ mri_download_dest }}"
    dest: "{{ mri_unarchive_dest }}"
    remote_src: yes
  when: mri_unarchive | default(false)

- name: Install Release
  ansible.builtin.copy:
    remote_src: true
    src: "{{ mri_executable_src }}"
    dest: "{{ mri_executable_dest }}"
    mode: "{{ mri_executable_mode | default('0755') }}"
