---
- name: Download Release
  ansible.builtin.get_url:
    url: "{{ release_installer_download_url }}"
    dest: "{{ release_installer_download_dest }}"

- name: Expand Archive
  ansible.builtin.unarchive:
    src: "{{ release_installer_download_dest }}"
    dest: "{{ release_installer_unarchive_dest }}"
    remote_src: yes
  when: release_installer_unarchive | default(false)

- name: Install Release
  ansible.builtin.copy:
    remote_src: true
    src: "{{ release_installer_executable_src }}"
    dest: "{{ release_installer_executable_dest }}"
    mode: "{{ release_installer_executable_mode | default('0755') }}"
