---
- name: Converge
  hosts: all
  gather_facts: true

  vars:
    release_installer_download_url: https://releases.hashicorp.com/terraform/1.3.3/terraform_1.3.3_linux_amd64.zip
    release_installer_download_dest: /tmp/terraform_1.3.3_linux_amd64.zip
    release_installer_unarchive: true
    release_installer_unarchive_dest: /tmp/terraform
    downloader_exec_src: /tmp/terraform
    downloader_exec_dest: /usr/bin/terraform

  tasks:
    - name: Install unzip
      ansible.builtin.apt:
        name: unzip
        state: present

    - name: Include role
      ansible.builtin.include_role:
        name: mirceanton.role_installer
