---
- name: Converge
  hosts: all
  gather_facts: true

  tasks:
    - name: Install unzip
      ansible.builtin.apt:
        name: unzip
        state: present
        update_cache: true

    - name: Include role
      ansible.builtin.include_role:
        name: mirceanton.downloader
      vars:
        downloader_download_url: https://releases.hashicorp.com/terraform/1.3.3/terraform_1.3.3_linux_amd64.zip
        downloader_download_dest: /tmp/terraform_1.3.3_linux_amd64.zip
        downloader_download_validate_certs: false
        downloader_unarchive: true
        downloader_unarchive_dest: /tmp
        downloader_executable_src: /tmp/terraform
        downloader_executable_dest: /usr/bin/terraform
        downloader_executable_mode: '0755'